### ISSUE TITLE
Support `paths` Github Filter pattern

### ISSUE THREAD

**Issue by zomars** [blend/require-conditional-status-checks#10]
Does the `paths` options accept a negated wildcard path or is it necessary to add a `paths-ignore` option? Thank you BTW this is very useful 🙏🏽

**Comment by zomars** [comment]
Sorry to bother, but does this follow the [Github Filter pattern](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet) ?

I'm finding some inconsistencies  between a regular check `path` and [this action](https://github.com/calcom/cal.com/blob/main/.github/workflows/required-checks.yml) `path`.

For example I have type check like this:

```yaml
name: Check types
on:
  pull_request_target:
    branches:
      - main
    paths:
      - '**.tsx?'
jobs:
  check-types:
    steps:
      - run: yarn type-check
```

and this on my conditional check:

```yaml
name: "Meta Workflow: Require Conditional Status Checks"

on:
  pull_request:
    branches:
      - main

jobs:
  required-checks:
    strategy:
      matrix:
        node: ["16.x"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - name: Ensure All Conditional Checks Have Passed
        uses: blend/require-conditional-status-checks@2022.02.04
        with:
          interval: 20s
          checks-yaml: |
            - job: check-types
              paths:
                - '**.tsx?'
```

This runs Check types when I modify a `.ts` or `.tsx` file but on the `required-checks` job, `check-types` doesn't appear as a required check.

Am I missing something? Thanks again for your attention 🙏🏽 

EDIT: 

Maybe I'm just tired but I'm testing with a simple PR that modifies a json and ts file:

<img width="705" alt="image" src="https://user-images.githubusercontent.com/3504472/177236896-f342a393-e17f-4f12-9eca-c9136681a803.png">


And according to my config it should run `check-types` 

<img width="564" alt="image" src="https://user-images.githubusercontent.com/3504472/177236996-0955fea2-7723-4dcc-978e-106c0cdb2697.png">

But actually is running ALL but `check-types`. Am I making sense?

<img width="609" alt="image" src="https://user-images.githubusercontent.com/3504472/177236867-9b84c73b-fc54-406e-b2cf-95bf4889bad2.png">
